## TenserFlow: Мат Операции

In [ ]:
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

In [5]:
import tensorflow as tf

### Initialization

In [11]:
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [7]:
x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3))
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [8]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [12]:
x = tf.ones((4, 3))
print(x)


tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


In [13]:
x = tf.zeros((3, 2, 5))
print(x)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 2, 5), dtype=float32)


In [18]:
x = tf.random.uniform((2, 2), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.92388046 0.44442916]
 [0.01177216 0.74455965]], shape=(2, 2), dtype=float32)


In [20]:
x = tf.random.normal((3, 3), mean=0, stddev=1)
print(tf.cast(x, dtype=tf.float64))

tf.Tensor(
[[ 1.38212919  0.03250717 -0.53851688]
 [-1.04308891 -0.99633753 -1.1919843 ]
 [-0.71122622  2.36879873 -0.00838318]], shape=(3, 3), dtype=float64)


In [21]:
x = tf.range(9)
x = tf.range(start=0, limit=10, delta=2)
print(x)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


### Math

In [26]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

In [28]:
z = tf.add(x, y)
z = x + y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [30]:
z = tf.subtract(x, y)
z = x - y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [31]:
z = tf.divide(x, y)
z = x / y
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [33]:
z = tf.multiply(x, y)
z = x * y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [34]:
z = tf.tensordot(x, y, axes=1)
z

<tf.Tensor: shape=(), dtype=int32, numpy=46>

### Reshaping

In [35]:

x = tf.range(9)

x = tf.reshape(x, (3, 3))

x = tf.transpose(x, perm=[1, 0])

In [36]:
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>